// actionTypes.js
export const SAVE_JOB_REQUEST = 'SAVE_JOB_REQUEST';
export const SAVE_JOB_SUCCESS = 'SAVE_JOB_SUCCESS';
export const SAVE_JOB_FAILURE = 'SAVE_JOB_FAILURE';

export const UNSAVE_JOB_REQUEST = 'UNSAVE_JOB_REQUEST';
export const UNSAVE_JOB_SUCCESS = 'UNSAVE_JOB_SUCCESS';
export const UNSAVE_JOB_FAILURE = 'UNSAVE_JOB_FAILURE';

export const GET_SAVED_JOBS_REQUEST = 'GET_SAVED_JOBS_REQUEST';
export const GET_SAVED_JOBS_SUCCESS = 'GET_SAVED_JOBS_SUCCESS';
export const GET_SAVED_JOBS_FAILURE = 'GET_SAVED_JOBS_FAILURE';
