export const CREATE_BLOG_REQUEST = 'CREATE_BLOG_REQUEST';
export const CREATE_BLOG_SUCCESS = 'CREATE_BLOG_SUCCESS';
export const CREATE_BLOG_FAILURE = 'CREATE_BLOG_FAILURE';

export const GETALL_BLOG_REQUEST = 'GETALL_BLOG_REQUEST';
export const GETALL_BLOG_SUCCESS = 'GETALL_BLOG_SUCCESS';
export const GETALL_BLOG_FAILURE = 'GETALL_BLOG_FAILURE';

export const GETALL_BY_ID_BLOG_REQUEST = 'GETALL_BY_ID_BLOG_REQUEST';
export const GETALL_BY_ID_BLOG_SUCCESS = 'GETALL_BY_ID_BLOG_SUCCESS';
export const GETALL_BY_ID_BLOG_FAILURE = 'GETALL_BY_ID_BLOG_FAILURE';

export const UPDATE_BLOG_REQUEST = 'UPDATE_BLOG_REQUEST';
export const UPDATE_BLOG_SUCCESS = 'UPDATE_BLOG_SUCCESS';
export const UPDATE_BLOG_FAILURE = 'UPDATE_BLOG_FAILURE';

export const DELETE_BLOG_REQUEST = 'DELETE_BLOG_REQUEST';
export const DELETE_BLOG_SUCCESS = 'DELETE_BLOG_SUCCESS';
export const DELETE_BLOG_FAILURE = 'DELETE_BLOG_FAILURE';
